<?php declare(strict_types=1);

use Yireo\ExampleHomepageColorWidget\Block\ExampleWidget;

/** @var ExampleWidget $block */

$productId = (int)str_replace('product/', '', $block->getData('product_id'));
$layoutName = $block->getNameInLayout();
$layoutHash = md5($layoutName);
$product = $block->getProductById($productId);
?>
<div class="container">
    <div class="fadeout-<?= $layoutHash ?> p-6 mb-8" x-data="fadeoutHeader()" x-init="init()">
        <h1 class="product-<?= $productId ?>" text-xl><?= $product->getName() ?></h1>
        <p><?= $product->getDescription() ?></p>
    </div>
</div>

<script>
    function fadeoutHeader() {
        return {
            init: function () {
                setTimeout((function () {
                    this.$el.classList.add('fadeout-highlight');
                }).bind(this), 1000);
            }
        }
    }
</script>

<style>
    .fadeout-<?= $layoutHash ?> {
        border: 10px solid <?= $block->getData('color1') ?>;
    }

    .fadeout-<?= $layoutHash ?>.fadeout-highlight {
        animation-duration: 1s;
        animation-name: changeBorderColor-<?= $layoutHash ?>;
        animation-iteration-count: infinite;
        animation-direction: alternate;
    }

    @keyframes changeBorderColor-<?= $layoutHash ?> {
        from {
            border-color: <?= $block->getData('color1'); ?>;
            transform: scale(1);
        }

        to {
            border-color: <?= $block->getData('color2'); ?>;
            transform: scale(1.01);
        }
    }
</style>
